name: "Stonks"

settings:
  base:
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    CLANG_ANALYZER_LOCALIZABILITY_EMPTY_CONTEXT: YES
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
    ENABLE_HARDENED_RUNTIME: YES
    DEVELOPMENT_TEAM: SGM5527A99
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: 1.1.0
    CURRENT_PROJECT_VERSION: 1.1.0

options:
  deploymentTarget:
    macOS: 12.0

attributes:
  ORGANIZATIONNAME: "Vladislav Lisianskii"

packages:

  Swinject:
    url: https://github.com/Swinject/Swinject
    from: 2.8.4

  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.21.0

  # Local packages

  ## Core
  Modules:
    path: Packages/Modules
    group: Local


targets:
  StonksTracker:
    platform: macOS
    type: application
    sources:
      - path: "StonksTracker"
        excludes:
          - "swiftgen.yml"
          - "**/*.secret"
    dependencies:
      - package: Swinject
      - package: Firebase
        products:
          - FirebaseAnalytics
          - FirebaseCrashlytics
      - package: Modules
        products:
          - AnalyticsService
          - StatusItemController
          - MenuBarView
          - CoinCapPriceService
          - UpdateService
          - Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tr1ckyf0x.stonks.tracker
        CODE_SIGN_ENTITLEMENTS: "StonksTracker/Resources/StonksTracker.entitlements"
    postBuildScripts:
      - name: "Crashlytics"
        basedOnDependencyAnalysis: false
        script: |
                ${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Info.plist
          - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist
          - $(TARGET_BUILD_DIR)/$(EXECUTABLE_PATH)
